/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RIdRouteImport } from './routes/r.$id'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedNotificationSettingsRouteImport } from './routes/_authenticated/notification-settings'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedImportGoodreadsRouteImport } from './routes/_authenticated/import-goodreads'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedCreatorsRouteImport } from './routes/_authenticated/creators'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAddRouteImport } from './routes/_authenticated/add'
import { Route as AuthenticatedAskIndexRouteImport } from './routes/_authenticated/ask.index'
import { Route as AuthenticatedProfileUsernameRouteImport } from './routes/_authenticated/profile.$username'
import { Route as AuthenticatedItemIdRouteImport } from './routes/_authenticated/item.$id'
import { Route as AuthenticatedAskIdRouteImport } from './routes/_authenticated/ask.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RIdRoute = RIdRouteImport.update({
  id: '/r/$id',
  path: '/r/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationSettingsRoute =
  AuthenticatedNotificationSettingsRouteImport.update({
    id: '/notification-settings',
    path: '/notification-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportGoodreadsRoute =
  AuthenticatedImportGoodreadsRouteImport.update({
    id: '/import-goodreads',
    path: '/import-goodreads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreatorsRoute = AuthenticatedCreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAddRoute = AuthenticatedAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAskIndexRoute = AuthenticatedAskIndexRouteImport.update({
  id: '/ask/',
  path: '/ask/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileUsernameRoute =
  AuthenticatedProfileUsernameRouteImport.update({
    id: '/profile/$username',
    path: '/profile/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItemIdRoute = AuthenticatedItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAskIdRoute = AuthenticatedAskIdRouteImport.update({
  id: '/ask/$id',
  path: '/ask/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/add': typeof AuthenticatedAddRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/creators': typeof AuthenticatedCreatorsRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/import': typeof AuthenticatedImportRoute
  '/import-goodreads': typeof AuthenticatedImportGoodreadsRoute
  '/map': typeof AuthenticatedMapRoute
  '/me': typeof AuthenticatedMeRoute
  '/notification-settings': typeof AuthenticatedNotificationSettingsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/r/$id': typeof RIdRoute
  '/ask/$id': typeof AuthenticatedAskIdRoute
  '/item/$id': typeof AuthenticatedItemIdRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/ask/': typeof AuthenticatedAskIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/add': typeof AuthenticatedAddRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/creators': typeof AuthenticatedCreatorsRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/import': typeof AuthenticatedImportRoute
  '/import-goodreads': typeof AuthenticatedImportGoodreadsRoute
  '/map': typeof AuthenticatedMapRoute
  '/me': typeof AuthenticatedMeRoute
  '/notification-settings': typeof AuthenticatedNotificationSettingsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/r/$id': typeof RIdRoute
  '/ask/$id': typeof AuthenticatedAskIdRoute
  '/item/$id': typeof AuthenticatedItemIdRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/ask': typeof AuthenticatedAskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/add': typeof AuthenticatedAddRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/creators': typeof AuthenticatedCreatorsRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/import-goodreads': typeof AuthenticatedImportGoodreadsRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/notification-settings': typeof AuthenticatedNotificationSettingsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/r/$id': typeof RIdRoute
  '/_authenticated/ask/$id': typeof AuthenticatedAskIdRoute
  '/_authenticated/item/$id': typeof AuthenticatedItemIdRoute
  '/_authenticated/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/_authenticated/ask/': typeof AuthenticatedAskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/add'
    | '/admin'
    | '/creators'
    | '/feed'
    | '/friends'
    | '/import'
    | '/import-goodreads'
    | '/map'
    | '/me'
    | '/notification-settings'
    | '/notifications'
    | '/r/$id'
    | '/ask/$id'
    | '/item/$id'
    | '/profile/$username'
    | '/ask/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/add'
    | '/admin'
    | '/creators'
    | '/feed'
    | '/friends'
    | '/import'
    | '/import-goodreads'
    | '/map'
    | '/me'
    | '/notification-settings'
    | '/notifications'
    | '/r/$id'
    | '/ask/$id'
    | '/item/$id'
    | '/profile/$username'
    | '/ask'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/add'
    | '/_authenticated/admin'
    | '/_authenticated/creators'
    | '/_authenticated/feed'
    | '/_authenticated/friends'
    | '/_authenticated/import'
    | '/_authenticated/import-goodreads'
    | '/_authenticated/map'
    | '/_authenticated/me'
    | '/_authenticated/notification-settings'
    | '/_authenticated/notifications'
    | '/r/$id'
    | '/_authenticated/ask/$id'
    | '/_authenticated/item/$id'
    | '/_authenticated/profile/$username'
    | '/_authenticated/ask/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RIdRoute: typeof RIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$id': {
      id: '/r/$id'
      path: '/r/$id'
      fullPath: '/r/$id'
      preLoaderRoute: typeof RIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notification-settings': {
      id: '/_authenticated/notification-settings'
      path: '/notification-settings'
      fullPath: '/notification-settings'
      preLoaderRoute: typeof AuthenticatedNotificationSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import-goodreads': {
      id: '/_authenticated/import-goodreads'
      path: '/import-goodreads'
      fullPath: '/import-goodreads'
      preLoaderRoute: typeof AuthenticatedImportGoodreadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creators': {
      id: '/_authenticated/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof AuthenticatedCreatorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/add': {
      id: '/_authenticated/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AuthenticatedAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ask/': {
      id: '/_authenticated/ask/'
      path: '/ask'
      fullPath: '/ask/'
      preLoaderRoute: typeof AuthenticatedAskIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/$username': {
      id: '/_authenticated/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AuthenticatedProfileUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/item/$id': {
      id: '/_authenticated/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof AuthenticatedItemIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ask/$id': {
      id: '/_authenticated/ask/$id'
      path: '/ask/$id'
      fullPath: '/ask/$id'
      preLoaderRoute: typeof AuthenticatedAskIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddRoute: typeof AuthenticatedAddRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCreatorsRoute: typeof AuthenticatedCreatorsRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedImportGoodreadsRoute: typeof AuthenticatedImportGoodreadsRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedNotificationSettingsRoute: typeof AuthenticatedNotificationSettingsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedAskIdRoute: typeof AuthenticatedAskIdRoute
  AuthenticatedItemIdRoute: typeof AuthenticatedItemIdRoute
  AuthenticatedProfileUsernameRoute: typeof AuthenticatedProfileUsernameRoute
  AuthenticatedAskIndexRoute: typeof AuthenticatedAskIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddRoute: AuthenticatedAddRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCreatorsRoute: AuthenticatedCreatorsRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedImportGoodreadsRoute: AuthenticatedImportGoodreadsRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedNotificationSettingsRoute:
    AuthenticatedNotificationSettingsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedAskIdRoute: AuthenticatedAskIdRoute,
  AuthenticatedItemIdRoute: AuthenticatedItemIdRoute,
  AuthenticatedProfileUsernameRoute: AuthenticatedProfileUsernameRoute,
  AuthenticatedAskIndexRoute: AuthenticatedAskIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RIdRoute: RIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
